name: yatl
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-175.0.dev <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^1.8.2
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {intl: ^0.17.0}
