name: yatl_flutter
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.17.0
  path: ^1.8.2
  yatl:
    git:
      url: https://github.com/HrX03/yatl
      path: yatl

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: