name: example
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-175.0.dev <3.0.0'

dependencies:
  yatl:
    git:
      url: https://github.com/HrX03/yatl
      path: yatl

  yatl_gen:
    path: ../

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^2.0.0
  test: ^1.16.0
